name: medix
description: MediX - vodič kroz lijekove bez obvezne prijave ili registracije.
publish_to: "none"
version: 0.3.1+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^22.3.1
  flutter_timezone: ^5.1.0
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/medications_official.json
    - assets/data/halmed_prices_2026.json
    - assets/data/icd10.json
